# Generated by Django 3.2.5 on 2021-08-27 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210827_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes_users',
        ),
        migrations.AddField(
            model_name='post',
            name='likes_users',
            field=models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
